package com.ystech.cqgtdag.model.news;

// Generated 2014-5-22 17:10:33 by Hibernate Tools 4.0.0

/**
 * Friendlink generated by hbm2java
 */
public class FriendLink implements java.io.Serializable {

	private Integer dbid;
	private String title;
	private String link;
	private String note;
	private String image;
	private Integer orderNum;

	public FriendLink() {
	}

	public FriendLink(String link) {
		this.link = link;
	}

	public FriendLink(String title, String link, String note, String image,
			Integer orderNum) {
		this.title = title;
		this.link = link;
		this.note = note;
		this.image = image;
		this.orderNum = orderNum;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

}
