package com.ystech.cqgtdag.model.news;

// Generated 2014-5-22 17:10:33 by Hibernate Tools 4.0.0

import java.util.Date;

import com.ystech.core.model.User;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer dbid;
	private NewsType newstype;
	private String title;
	private String content;
	private User releasePerson;
	private Date releaseDate;
	private Integer readNum;
	private Boolean isStop;
	private String titlePicture;
	private String attach;
	private String introduction;
	private Integer orderNum;
	private Date modifyDate;
	//索引高亮用
	private String contentText;
	public News() {
	}

	public News(String title) {
		this.title = title;
	}

	public News(NewsType newstype, String title, String content,
			Integer releasePerson, Date releaseDate, Integer readNum,
			Boolean isBannerPicture, Boolean isOnTime, Boolean isLatestNew,
			Boolean isStop, String titlePicture, String attach,
			String introduction, String contentText) {
		this.newstype = newstype;
		this.title = title;
		this.content = content;
		this.releaseDate = releaseDate;
		this.readNum = readNum;
		this.isStop = isStop;
		this.titlePicture = titlePicture;
		this.attach = attach;
		this.introduction = introduction;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public NewsType getNewstype() {
		return this.newstype;
	}

	public void setNewstype(NewsType newstype) {
		this.newstype = newstype;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public User getReleasePerson() {
		return this.releasePerson;
	}

	public void setReleasePerson(User releasePerson) {
		this.releasePerson = releasePerson;
	}

	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Integer getReadNum() {
		return this.readNum;
	}

	public void setReadNum(Integer readNum) {
		this.readNum = readNum;
	}


	public Boolean getIsStop() {
		return this.isStop;
	}

	public void setIsStop(Boolean isStop) {
		this.isStop = isStop;
	}

	public String getTitlePicture() {
		return this.titlePicture;
	}

	public void setTitlePicture(String titlePicture) {
		this.titlePicture = titlePicture;
	}

	public String getAttach() {
		return this.attach;
	}

	public void setAttach(String attach) {
		this.attach = attach;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}


	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getContentText() {
		return contentText;
	}

	public void setContentText(String contentText) {
		this.contentText = contentText;
	}


}
