package com.ystech.cqgtdag.model.news;

// Generated 2014-5-22 17:10:33 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Newstype generated by hbm2java
 */
public class NewsType implements java.io.Serializable {

	private Integer dbid;
	private String name;
	private String note;
	private NewsType parent;
	private Integer orderNum;
	private Set newses = new HashSet(0);

	public NewsType() {
	}

	public NewsType(String name) {
		this.name = name;
	}

	public NewsType(String name, String note, Integer parentId, Set newses) {
		this.name = name;
		this.note = note;
		this.newses = newses;
	}

	public Integer getDbid() {
		return this.dbid;
	}

	public void setDbid(Integer dbid) {
		this.dbid = dbid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}


	public Set getNewses() {
		return this.newses;
	}

	public void setNewses(Set newses) {
		this.newses = newses;
	}

	public NewsType getParent() {
		return parent;
	}

	public void setParent(NewsType parent) {
		this.parent = parent;
	}

	public Integer getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

}
